"""Add suggested_instructions column to tasks table

Revision ID: 3174d894ab5b
Revises: d1db3d539d8b
Create Date: 2025-02-04 16:26:22.982568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3174d894ab5b'
down_revision: Union[str, None] = 'd1db3d539d8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('suggested_instructions', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'suggested_instructions')
    # ### end Alembic commands ###